---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-download-model-yolo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
    - name: job-download-model-yolo
      image: registry.access.redhat.com/ubi9/python-312:latest
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-auth
              key: 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
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
          args:
            - -c
            - |
                set -euo pipefail
                pip install huggingface_hub
                python - <<'PYCODE'
                import pathlib
                import shutil
                from huggingface_hub import hf_hub_download

                # 修正ポイント
                repo_id = "Hirai-Labs/YOLOv8m-OpenVINO"
                filename = "model.xml"
                weights = "model.bin"

                target = pathlib.Path("/mnt/model/yolov8m/1/model.xml")
                target_weights = target.with_suffix(".bin")
                target.parent.mkdir(parents=True, exist_ok=True)

                downloaded = hf_hub_download(
                    repo_id=repo_id,
                    filename=filename,
                    local_dir=target.parent,
                    local_dir_use_symlinks=False,
                )
                print(f"Downloaded: {downloaded}")
                shutil.copy2(downloaded, target)
                print(f"Copied to: {target}")

                downloaded_weights = hf_hub_download(
                    repo_id=repo_id,
                    filename=weights,
                    local_dir=target.parent,
                    local_dir_use_symlinks=False,
                )
                print(f"Downloaded weights: {downloaded_weights}")
                shutil.copy2(downloaded_weights, target_weights)
                print(f"Copied weights to: {target_weights}")
                PYCODE
                cat <<'EOCONFIG' > /mnt/model/yolov8m/config.pbtxt
                name: "yolov8m"
                platform: "openvino_ir"
                max_batch_size: 1
                input [
                  {
                    name: "images"
                    data_type: TYPE_FP32
                    format: FORMAT_NCHW
                    dims: [3, 640, 640]
                  }
                ]
                output [
                  {
                    name: "output0"
                    data_type: TYPE_FP32
                    dims: [84, 8400]
                  }
                ]
                instance_group [
                  { kind: KIND_GPU }
                ]
                EOCONFIG
                sync
          volumeMounts:
            - name: model-storage-yolo
              mountPath: /mnt
      volumes:
        - name: model-storage-yolo
          persistentVolumeClaim:
            claimName: model-storage-yolo
      restartPolicy: Never
