---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-yolo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
