---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: OpenVINO Model Server for YOLO
    opendatahub.io/template-name: openvino-yolo-runtime
    openshift.io/display-name: OpenVINO Model Server for YOLO
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  labels:
    opendatahub.io/dashboard: "true"
  name: openvino-runtime
spec:
  multiModel: false
  protocolVersions:
    - grpc-v2
    - http-v2
  supportedModelFormats:
    - name: openvino_ir
      autoSelect: true
  containers:
    - name: kserve-container
      image: openvino/model_server:2025.2
      command:
        - /ovms
      args:
        - --model_path=/mnt/models
        - --model_name={{.Name}}
        - --port=9000
        - --rest_port=8000
        - --target_device=GPU
        - --log_level=INFO
      ports:
        - containerPort: 8000
          name: http2
          protocol: TCP
        - containerPort: 9000
          name: grpc
          protocol: TCP
