apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobile-report-app-md
  labels:
    app: mobile-report-app
    component: mobile-report-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
